# -*- coding: utf-8 -*-
"""data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17oVkVkEcwjHqGykdiAPgKA9xMlqY7twI
"""

pip install openpyxl

import os
os.listdir()

import pandas as pd

df = pd.read_excel("train(1).xlsx")
print(df.columns)

import os
import time
import pandas as pd
import requests

# ================= CONFIG =================
EXCEL_FILE = "train(1).xlsx"
OUTPUT_DIR = "mapbox_images"

IMAGE_SIZE = "512x512"
ZOOM = 18

MAPBOX_TOKEN = "enter your token"

DELAY = 0.15          # seconds between requests
MAX_RETRIES = 3
TIMEOUT = 10          # seconds
# =========================================

os.makedirs(OUTPUT_DIR, exist_ok=True)

df = pd.read_excel(EXCEL_FILE)

print("Total rows:", len(df))
print("Downloading satellite images...")

failed_indices = []


def download_image(lat, lon, idx):
    # Skip invalid coordinates
    if pd.isna(lat) or pd.isna(lon):
        failed_indices.append(idx)
        return

    filepath = f"{OUTPUT_DIR}/img_{idx}.png"

    # Resume-safe: skip if already exists
    if os.path.exists(filepath):
        return

    url = (
        f"https://api.mapbox.com/styles/v1/mapbox/satellite-v9/static/"
        f"{lon},{lat},{ZOOM}/{IMAGE_SIZE}"
        f"?access_token={MAPBOX_TOKEN}"
    )

    for attempt in range(MAX_RETRIES):
        try:
            response = requests.get(url, timeout=TIMEOUT)

            if response.status_code == 200:
                with open(filepath, "wb") as f:
                    f.write(response.content)
                return

        except requests.exceptions.RequestException:
            pass

        time.sleep(0.3)  # small backoff

    failed_indices.append(idx)


for idx, row in df.iterrows():
    download_image(row["lat"], row["long"], idx)
    time.sleep(DELAY)


# Save failed indices for transparency
if failed_indices:
    pd.Series(failed_indices, name="failed_index").to_csv(
        "failed_image_indices.csv", index=False
    )
    print(f" Failed downloads: {len(failed_indices)} (saved to CSV)")

print(" Image download process completed.")

import os
os.listdir("mapbox_images")[:5]

!zip -r mapbox_images.zip mapbox_images

from google.colab import files
files.download("mapbox_images.zip")
